name: 3NightsToDie
main: fr.azrotho.threenightstodie.ThreeNightsToDiePlugin
version: 1.0
author: Azrotho
commands:
  debug:
    description: Debug command
    usage: /<command>
    aliases:
    - d
  vote:
    description: Vote command
    usage: /vote <player>
    aliases:
    - v
  broadcast:
    description: Broadcast command
    usage: /broadcast <message>
    aliases:
    - b
    - bc